name: Deploy Laravel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download my code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Prepare SQLite file for artisan scripts
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Install PHP packages
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JS packages
        run: npm ci

      - name: Build CSS and JS
        run: npm run build

      - name: Upload files to server via FTP (attempt 1)
        id: ftp_deploy_attempt_1
        continue-on-error: true
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ${{ secrets.FTP_PROTOCOL || 'ftp' }}
          log-level: verbose
          local-dir: ./          # upload from project root
          server-dir: /etsmsfbusiness.com/app/ # where to upload on server
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env
            **/storage/logs/**
            **/storage/framework/sessions/**

      - name: Upload files to server via FTP (retry)
        if: steps.ftp_deploy_attempt_1.outcome == 'failure'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ${{ secrets.FTP_PROTOCOL || 'ftp' }}
          log-level: verbose
          local-dir: ./          # upload from project root
          server-dir: /etsmsfbusiness.com/app/   # where to upload on server
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env
            **/storage/logs/**
            **/storage/framework/sessions/**
